{{-- @extends('frontend.layouts.app')

@section('content')
    <div class="container mt-5">
        @if (isset($error))
            <div class="alert alert-danger">{{ $error }}</div>
        @else
            <div class="card shadow-sm border-{{ $data['status'] === 'Approved' ? 'success' : 'danger' }}">
                <div class="card-header bg-{{ $data['status'] === 'Approved' ? 'success' : 'danger' }} text-white">
                    <h5 class="mb-0">Leave Verification Result</h5>
                </div>
                <div class="card-body">
                    <p><strong>Name:</strong> {{ $data['name'] }}</p>
                    <p><strong>Status:</strong>
                        <span class="badge bg-{{ $data['status'] === 'Approved' ? 'success' : 'danger' }}">
                            {{ $data['status'] }}
                        </span>
                    </p>
                    <p><strong>Remarks:</strong> {{ $data['remarks'] }}</p>
                    <p><strong>Action Date:</strong> {{ $data['action_at'] }}</p>
                </div>
            </div>
        @endif
    </div>
@endsection --}}

@extends('frontend.layouts.app')

@section('content')
<div class="container mt-5">
    @if(isset($error))
        <div class="alert alert-danger text-center">
            <strong>{{ $error }}</strong>
        </div>
    @else
        <div class="card shadow-lg border-0">
            <div class="card-header bg-primary text-white">
                <h4 class="mb-0">Leave Verification Result</h4>
            </div>
            <div class="card-body">
                <div class="row mb-3">
                    <div class="col-md-6">
                        <p><strong>Name:</strong> {{ $data['name'] }}</p>
                        <p><strong>Email:</strong> {{ $data['email'] }}</p>
                        <p><strong>Mobile:</strong> {{ $data['mobile'] }}</p>
                        <p><strong>Course:</strong> {{ $data['course'] }}</p>
                        <p><strong>Department:</strong> {{ $data['department'] }}</p>
                    </div>
                    <div class="col-md-6">
                        <p><strong>Leave Start:</strong> {{ $data['start_date'] }}</p>
                        <p><strong>Leave End:</strong> {{ $data['end_date'] }}</p>
                        <p><strong>Applied On:</strong> {{ $data['applied_on'] }}</p>
                        <p><strong>Status:</strong> 
                            <span class="badge bg-{{ strtolower($data['status']) === 'approved' ? 'success' : (strtolower($data['status']) === 'pending' ? 'warning' : 'danger') }}">
                                {{ $data['status'] }}
                            </span>
                        </p>
                        <p><strong>Remarks:</strong> {{ $data['remarks'] }}</p>
                        <p><strong>Action Date:</strong> {{ $data['action_at'] }}</p>
                    </div>
                </div>
            </div>
            <div class="card-footer text-muted text-center">
                <small>Generated by Leave Management System • {{ now()->format('d M Y, h:i A') }}</small>
            </div>
        </div>
    @endif
</div>
@endsection
