@extends('frontend.layouts.app')

@section('content')
<div class="container py-5">
    @if(isset($error))
        <div class="alert alert-danger text-center shadow-sm">
            <i class="bi bi-exclamation-triangle-fill"></i> {{ $error }}
        </div>
    @else
        <div class="card shadow-lg border-0 rounded-3">
            <div class="card-header bg-gradient-primary text-dark d-flex justify-content-between align-items-center">
                <h4 class="mb-0"><i class="bi bi-file-earmark-check"></i> Leave Verification Result</h4>
                <span class="badge bg-{{ strtolower($data['status']) === 'approved' ? 'success' : (strtolower($data['status']) === 'pending' ? 'warning' : 'danger') }} fs-6">
                    {{ $data['status'] }}
                </span>
            </div>
            <div class="card-body">
                <div class="row g-4">
                    <!-- Resident Info -->
                    <div class="col-md-6">
                        <h5 class="text-secondary border-bottom pb-2">Resident Information</h5>
                        <ul class="list-unstyled mb-0">
                            <li><strong>Name:</strong> {{ $data['name'] }}</li>
                            <li><strong>Email:</strong> {{ $data['email'] }}</li>
                            <li><strong>Mobile:</strong> {{ $data['mobile'] }}</li>
                            <li><strong>Course:</strong> {{ $data['course'] }}</li>
                            <li><strong>Department:</strong> {{ $data['department'] }}</li>
                        </ul>
                    </div>

                    <!-- Leave Info -->
                    <div class="col-md-6">
                        <h5 class="text-secondary border-bottom pb-2">Leave Details</h5>
                        <ul class="list-unstyled mb-0">
                            <li><strong>Start Date:</strong> {{ $data['start_date'] }}</li>
                            <li><strong>End Date:</strong> {{ $data['end_date'] }}</li>
                            <li><strong>Applied On:</strong> {{ $data['applied_on'] }}</li>
                            <li><strong>Remarks:</strong> {{ $data['remarks'] }}</li>
                            <li><strong>Action Date:</strong> {{ $data['action_at'] }}</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="card-footer text-center text-muted">
                <small>Generated by Leave Management System • {{ now()->format('d M Y, h:i A') }}</small>
            </div>
        </div>
    @endif
</div>
@endsection
